using System;using System.Collections.Generic;using System.Globalization;using ForteMove.Models.Common;using ForteMove.Models.Drivers;using ForteMove.Web.Infrastructure;
namespace ForteMove.Web.Admin.Drivers
{
    public partial class EditDriver:AdminPage
    {
        private long Id{get{long value;return long.TryParse(Request.QueryString["id"],out value)?value:0;}}
        protected void Page_Load(object sender,EventArgs e){if(!IsPostBack)Bind();}
        private void Bind(){ForteMove.Models.Drivers.Driver driver=ServiceFactory.CreateDriverService().GetDriver(Id);if(driver==null){Response.Redirect(ResolveUrl("~/Admin/Drivers/DriverList.aspx"),true);return;}txtFirstName.Text=driver.FirstName;txtLastName.Text=driver.LastName;txtEmail.Text=driver.Email;txtPhone.Text=driver.PhoneNumber;txtDateOfBirth.Text=driver.DateOfBirth.ToString("yyyy-MM-dd");ddlAvailability.SelectedValue=driver.AvailabilityStatus.ToString();txtLicenceNumber.Text=driver.LicenceNumber;ddlLicenceCode.SelectedValue=driver.LicenceCode.ToString();txtLicenceExpiry.Text=driver.LicenceExpiryDate.ToString("yyyy-MM-dd");txtPrdpNumber.Text=driver.PrdpNumber;txtPrdpExpiry.Text=driver.PrdpExpiryDate.ToString("yyyy-MM-dd");hidUserRv.Value=Convert.ToBase64String(driver.UserRowVersion);hidStaffRv.Value=Convert.ToBase64String(driver.StaffRowVersion);hidDriverRv.Value=Convert.ToBase64String(driver.DriverRowVersion);}
        protected void btnSave_Click(object sender,EventArgs e){IList<ValidationError> binding=new List<ValidationError>();DriverAvailabilityStatus availability;DriverLicenceCode licence;var result=ServiceFactory.CreateDriverService().UpdateDriver(new UpdateDriverRequest{DriverProfileId=Id,FirstName=txtFirstName.Text,LastName=txtLastName.Text,Email=txtEmail.Text,PhoneNumber=txtPhone.Text,DateOfBirth=ParseDate(txtDateOfBirth.Text,"DateOfBirth",binding),AvailabilityStatus=Enum.TryParse(ddlAvailability.SelectedValue,out availability)?availability:(DriverAvailabilityStatus?)null,LicenceNumber=txtLicenceNumber.Text,LicenceCode=Enum.TryParse(ddlLicenceCode.SelectedValue,out licence)?licence:(DriverLicenceCode?)null,LicenceExpiryDate=ParseDate(txtLicenceExpiry.Text,"LicenceExpiryDate",binding),PrdpNumber=txtPrdpNumber.Text,PrdpExpiryDate=ParseDate(txtPrdpExpiry.Text,"PrdpExpiryDate",binding),UserRowVersion=ParseRv(hidUserRv.Value),StaffRowVersion=ParseRv(hidStaffRv.Value),DriverRowVersion=ParseRv(hidDriverRv.Value)},CurrentPrincipalContext.UserAccountId);if(binding.Count>0){Show(binding);return;}if(!result.Succeeded){Show(result.Errors);return;}FlashMessageStore.Put(Session,"Driver details were updated."+(result.HasWarnings?" "+string.Join(" ",result.Warnings):string.Empty),result.HasWarnings);Response.Redirect(ResolveUrl("~/Admin/Drivers/DriverDetails.aspx?id="+Id),true);}
        private static DateTime? ParseDate(string text,string field,IList<ValidationError> errors){DateTime value;if(DateTime.TryParseExact(text,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out value))return value;errors.Add(new ValidationError(field,"Enter a valid date."));return null;}private static byte[] ParseRv(string value){try{return Convert.FromBase64String(value);}catch{return null;}}private void Show(IEnumerable<ValidationError> errors){pnlErrors.Visible=true;rptErrors.DataSource=errors;rptErrors.DataBind();}
    }
}
