<%@ Page Title="Change schedule" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="ChangeSchedule.aspx.cs" Inherits="ForteMove.Web.Admin.Scheduling.ChangeSchedule" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="pnlNotFound" runat="server" CssClass="app-panel empty-state" Visible="false"><h1>Schedule not found</h1><p>The requested active Schedule is unavailable.</p><a class="btn btn-primary" href="<%= ResolveUrl("~/Admin/Scheduling/ScheduleList.aspx") %>">Return to schedules</a></asp:Panel>
    <asp:Panel ID="pnlEditor" runat="server" Visible="false">
        <header class="page-heading"><div><p class="section-kicker">Scheduling</p><h1>Change <asp:Literal ID="litScheduleCode" runat="server" /></h1><p><asp:Literal ID="litRoute" runat="server" /></p></div></header>
        <asp:Panel ID="pnlErrors" runat="server" CssClass="alert alert-danger validation-summary" role="alert" Visible="false" tabindex="-1"><div class="validation-summary-heading"><span class="alert-icon" aria-hidden="true">!</span><strong>Review the schedule change</strong></div><ul><asp:Repeater ID="rptErrors" runat="server"><ItemTemplate><li><%#: Eval("Message") %></li></ItemTemplate></asp:Repeater></ul></asp:Panel>
        <div class="form-layout schedule-builder-layout">
            <section class="app-panel form-panel"><div class="panel-heading"><span class="panel-step">01</span><div><h2>Revised service pattern</h2><p>Choose when the change takes effect and define the new recurring pattern.</p></div></div><div class="row g-4">
                <div class="col-md-6"><asp:Label runat="server" AssociatedControlID="txtChangeDate" CssClass="form-label required-label" Text="Changes take effect from" /><asp:TextBox ID="txtChangeDate" runat="server" CssClass="form-control" TextMode="Date" /></div>
                <div class="col-md-6"><asp:Label runat="server" AssociatedControlID="txtEndDate" CssClass="form-label required-label" Text="Effective end date" /><asp:TextBox ID="txtEndDate" runat="server" CssClass="form-control" TextMode="Date" /></div>
                <div class="col-12"><span class="form-label required-label">Operating days</span><asp:CheckBoxList ID="cblOperatingDays" runat="server" CssClass="day-selector" RepeatDirection="Horizontal" RepeatLayout="Flow"><asp:ListItem Text="Monday" Value="1" /><asp:ListItem Text="Tuesday" Value="2" /><asp:ListItem Text="Wednesday" Value="3" /><asp:ListItem Text="Thursday" Value="4" /><asp:ListItem Text="Friday" Value="5" /><asp:ListItem Text="Saturday" Value="6" /><asp:ListItem Text="Sunday" Value="0" /></asp:CheckBoxList></div>
                <div class="col-12"><span class="form-label required-label">Departure times</span><asp:Panel ID="pnlNoDepartures" runat="server" CssClass="compact-empty">No departure times added.</asp:Panel><asp:Repeater ID="rptDepartures" runat="server" OnItemCommand="rptDepartures_ItemCommand"><HeaderTemplate><div class="departure-chip-list"></HeaderTemplate><ItemTemplate><span class="departure-chip"><strong><%#: Eval("Display") %></strong><asp:LinkButton runat="server" CommandName="Remove" CommandArgument='<%# Eval("Value") %>' Text="Remove" CssClass="btn btn-link btn-sm" CausesValidation="false" /></span></ItemTemplate><FooterTemplate></div></FooterTemplate></asp:Repeater><div class="inline-input-row"><asp:TextBox ID="txtDepartureTime" runat="server" CssClass="form-control" TextMode="Time" step="60" /><asp:LinkButton ID="btnAddDeparture" runat="server" CssClass="btn btn-outline-primary" Text="Add departure" CausesValidation="false" OnClick="btnAddDeparture_Click" /></div></div>
                <div class="col-md-6"><asp:Label runat="server" AssociatedControlID="ddlBusCategory" CssClass="form-label" Text="Preferred bus category" /><asp:DropDownList ID="ddlBusCategory" runat="server" CssClass="form-select" /></div>
                <div class="col-md-6"><asp:Label runat="server" AssociatedControlID="txtExpectedCapacity" CssClass="form-label" Text="Expected capacity" /><asp:TextBox ID="txtExpectedCapacity" runat="server" CssClass="form-control" TextMode="Number" min="1" step="1" /></div>
            </div></section>
            <asp:Panel ID="pnlImpact" runat="server" CssClass="app-panel preview-panel" Visible="false" role="status"><p class="section-kicker">Change impact</p><h2>Review what will happen</h2><ul class="impact-list"><li><strong><asp:Literal ID="litReplaceCount" runat="server" /></strong> future Trips will be replaced.</li><li><strong><asp:Literal ID="litGenerateCount" runat="server" /></strong> Trips will be generated from the revised pattern.</li><li><strong><asp:Literal ID="litProtectedCount" runat="server" /></strong> future Trips will be kept and marked for review.</li><li><strong>0</strong> historical Trips will change.</li></ul></asp:Panel>
            <div class="form-actions"><asp:HyperLink ID="lnkCancel" runat="server" CssClass="btn btn-outline-secondary" Text="Cancel" /><asp:Button ID="btnReview" runat="server" CssClass="btn btn-outline-primary" Text="Review changes" OnClick="btnReview_Click" /><asp:Button ID="btnApply" runat="server" CssClass="btn btn-primary" Text="Apply schedule change" Enabled="false" OnClick="btnApply_Click" /></div>
        </div>
    </asp:Panel>
</asp:Content>
