<%@ Page Title="Journey details" Language="C#" MasterPageFile="~/Passenger/Passenger.Master" AutoEventWireup="true" CodeBehind="JourneyDetails.aspx.cs" Inherits="ForteMove.Web.Passenger.JourneyDetailsPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
<header class="passenger-heading page-heading-with-action"><div><p class="section-kicker">Journey review</p><h1><asp:Literal ID="litRoute" runat="server" /></h1><p><asp:Literal ID="litEndpoints" runat="server" /></p></div><a class="btn btn-outline-secondary" href="<%= ResolveUrl("~/Passenger/Journeys.aspx") %>">Back to journeys</a></header>
<asp:Panel ID="pnlMessage" runat="server" CssClass="alert alert-danger" Visible="false"><asp:Repeater ID="rptErrors" runat="server"><ItemTemplate><div><%#: Eval("Message") %></div></ItemTemplate></asp:Repeater></asp:Panel>
<asp:Panel ID="pnlDetails" runat="server" Visible="false">
<section class="passenger-review-card"><div class="route-summary-grid"><div><span>Date</span><strong><asp:Literal ID="litDate" runat="server" /></strong></div><div><span>Departure</span><strong><asp:Literal ID="litDeparture" runat="server" /></strong></div><div><span>Expected finish</span><strong><asp:Literal ID="litFinish" runat="server" /></strong></div><div><span>Status</span><strong><asp:Literal ID="litStatus" runat="server" /></strong></div><div><span>Fare</span><strong><asp:Literal ID="litFare" runat="server" /></strong></div><div><span>Seats remaining</span><strong><asp:Literal ID="litSeats" runat="server" /></strong></div></div><asp:Panel ID="pnlDelay" runat="server" CssClass="alert alert-warning mt-3" Visible="false"><asp:Literal ID="litDelay" runat="server" /></asp:Panel></section>
<section class="app-panel mt-4"><h2>Wallet review</h2><div class="wallet-review"><div><span>Current balance</span><strong><asp:Literal ID="litWalletBalance" runat="server" /></strong></div><div><span>After purchase</span><strong><asp:Literal ID="litBalanceAfter" runat="server" /></strong></div></div><asp:Panel ID="pnlUnavailable" runat="server" CssClass="alert alert-warning mt-3" Visible="false"><asp:Literal ID="litUnavailable" runat="server" /></asp:Panel><asp:Panel ID="pnlInsufficient" runat="server" CssClass="alert alert-warning mt-3" Visible="false">Your wallet needs more funds for this Ticket. <a href="<%= ResolveUrl("~/Passenger/Wallet.aspx") %>">Top up wallet</a>.</asp:Panel><div class="form-actions"><asp:Button ID="btnPurchase" runat="server" CssClass="btn btn-primary btn-lg" Text="Purchase Ticket" OnClick="btnPurchase_Click"/><a class="btn btn-outline-secondary" href="<%= ResolveUrl("~/Passenger/Journeys.aspx") %>">Not now</a></div></section>
</asp:Panel>
<asp:Panel ID="pnlNotFound" runat="server" CssClass="app-panel empty-state" Visible="false"><h2>Journey unavailable</h2><p>This journey could not be found.</p><a class="btn btn-primary" href="<%= ResolveUrl("~/Passenger/Journeys.aspx") %>">Find another journey</a></asp:Panel>
</asp:Content>
