<%@ Page Title="Wallet" Language="C#" MasterPageFile="~/Passenger/Passenger.Master" AutoEventWireup="true" CodeBehind="Wallet.aspx.cs" Inherits="ForteMove.Web.Passenger.Wallet" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
<header class="passenger-heading"><p class="section-kicker">ForteMove wallet</p><h1>Wallet</h1><p>Use the simulated top-up to prepare funds for your Tickets.</p></header>
<asp:Panel ID="pnlMessage" runat="server" CssClass="alert" Visible="false"><asp:Literal ID="litMessage" runat="server" /></asp:Panel>
<section class="passenger-balance-card"><div><span>Available balance</span><strong><asp:Literal ID="litBalance" runat="server" /></strong></div></section>
<section class="app-panel form-panel mt-4"><h2>Simulated top-up</h2><p class="text-secondary">No payment card or real payment gateway is used.</p><div class="row g-3 align-items-end"><div class="col-sm-7"><asp:Label runat="server" AssociatedControlID="txtAmount" CssClass="form-label" Text="Top-up amount"/><div class="input-group"><span class="input-group-text">R</span><asp:TextBox ID="txtAmount" runat="server" CssClass="form-control" TextMode="Number" step="0.01" min="0.01"/></div></div><div class="col-sm-5"><asp:Button ID="btnReview" runat="server" CssClass="btn btn-outline-primary w-100" Text="Review top-up" OnClick="btnReview_Click"/></div></div>
<asp:Panel ID="pnlReview" runat="server" CssClass="wallet-topup-review mt-4" Visible="false"><h3 class="h5">Confirm top-up</h3><div class="wallet-review"><div><span>Current balance</span><strong><asp:Literal ID="litBefore" runat="server"/></strong></div><div><span>Top-up</span><strong><asp:Literal ID="litAmount" runat="server"/></strong></div><div><span>New balance</span><strong><asp:Literal ID="litAfter" runat="server"/></strong></div></div><div class="form-actions"><asp:Button ID="btnConfirm" runat="server" CssClass="btn btn-primary" Text="Confirm simulated top-up" OnClick="btnConfirm_Click"/><asp:LinkButton ID="btnCancel" runat="server" CssClass="btn btn-outline-secondary" Text="Cancel" CausesValidation="false" OnClick="btnCancel_Click"/></div></asp:Panel></section>
<section class="app-panel mt-4"><h2>Wallet activity</h2><asp:Repeater ID="rptTransactions" runat="server"><ItemTemplate><div class="wallet-entry"><div><strong><%#: FormatTransaction(Eval("TransactionType")) %></strong><span><%#: Eval("WalletTransactionCode") %> · <%#: FormatOccurred(Eval("OccurredUtc")) %></span><span><%#: Eval("RouteName") %></span></div><div class="text-end"><strong><%#: FormatAmount(Eval("TransactionType"),Eval("Amount")) %></strong><span>Balance <%#: Eval("BalanceAfter","{0:C}") %></span></div></div></ItemTemplate></asp:Repeater><asp:Panel ID="pnlNoTransactions" runat="server" CssClass="compact-empty"><p>No wallet activity yet.</p></asp:Panel></section>
</asp:Content>
