<%@ Page Title="Assignment queue" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="AssignmentQueue.aspx.cs" Inherits="ForteMove.Web.Admin.Assignments.AssignmentQueue" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
<header class="page-heading"><p class="section-kicker">Assignments</p><h1>Assignment queue</h1><p>Review explainable Driver and bus recommendations before confirming them.</p></header>
<asp:Panel ID="pnlMessage" runat="server" CssClass="alert alert-danger" Visible="false"><asp:Literal ID="litMessage" runat="server"/></asp:Panel>
<section class="app-panel filter-panel"><div class="row g-3 align-items-end"><div class="col-sm-4"><label class="form-label">Service date</label><asp:TextBox ID="txtDate" runat="server" CssClass="form-control" TextMode="Date"/></div><div class="col-sm-3"><asp:Button ID="btnLoad" runat="server" CssClass="btn btn-primary" Text="Load Trips" OnClick="btnLoad_Click"/></div></div></section>
<asp:Panel ID="pnlReview" runat="server" CssClass="app-panel mt-4" Visible="false"><h2>Schedule-change review required</h2><p>These Trips are protected from automatic regeneration.</p><asp:Repeater ID="rptReview" runat="server"><ItemTemplate><div class="border-top py-3"><strong><%#: Eval("TripCode") %></strong> · <%#: Eval("RouteCode") %> · <%#: Eval("ScheduledDepartureTime", "{0:hh\\:mm}") %> <a class="ms-2" href='<%# ResolveUrl("~/Admin/Assignments/AssignmentDetails.aspx?id="+Eval("TripId")) %>'>Review Trip</a></div></ItemTemplate></asp:Repeater></asp:Panel>
<section class="app-panel mt-4"><div class="panel-heading"><div><h2>Recommendations</h2><p><asp:Literal ID="litEvaluated" runat="server"/></p></div></div>
<asp:Repeater ID="rptRecommendations" runat="server"><ItemTemplate><article class="border-top py-3"><div class="row align-items-center"><div class="col-auto">
<asp:CheckBox ID="chkSelect" runat="server" Visible='<%# Eval("HasRecommendation") %>'/>
<asp:HiddenField ID="hidTripId" runat="server" Value='<%# RecommendationValue(Container.DataItem,"TripId") %>'/><asp:HiddenField ID="hidBusId" runat="server" Value='<%# RecommendationValue(Container.DataItem,"BusId") %>'/><asp:HiddenField ID="hidDriverId" runat="server" Value='<%# RecommendationValue(Container.DataItem,"DriverId") %>'/>
<asp:HiddenField ID="hidTripRv" runat="server" Value='<%# RecommendationValue(Container.DataItem,"TripRv") %>'/><asp:HiddenField ID="hidBusRv" runat="server" Value='<%# RecommendationValue(Container.DataItem,"BusRv") %>'/><asp:HiddenField ID="hidDriverRv" runat="server" Value='<%# RecommendationValue(Container.DataItem,"DriverRv") %>'/><asp:HiddenField ID="hidUserRv" runat="server" Value='<%# RecommendationValue(Container.DataItem,"UserRv") %>'/><asp:HiddenField ID="hidStaffRv" runat="server" Value='<%# RecommendationValue(Container.DataItem,"StaffRv") %>'/>
</div><div class="col"><strong><%#: Eval("Trip.TripCode") %> · <%#: Eval("Trip.RouteCode") %></strong><span class="cell-secondary"><%#: Eval("Trip.ScheduledDepartureTime", "{0:hh\\:mm}") %>–<%#: Eval("Trip.ExpectedFinishLocal", "{0:g}") %></span><asp:Panel runat="server" Visible='<%# Eval("HasRecommendation") %>'><span><%#: RecommendationLabel(Container.DataItem) %></span><span class="cell-secondary"><%#: Eval("Explanation") %></span></asp:Panel><asp:Panel runat="server" Visible='<%# !(bool)Eval("HasRecommendation") %>' CssClass="text-danger"><%#: Eval("ExclusionReason") %></asp:Panel></div><div class="col-auto"><a href='<%# ResolveUrl("~/Admin/Assignments/AssignmentDetails.aspx?id="+Eval("Trip.TripId")) %>'>Review</a></div></div></article></ItemTemplate></asp:Repeater>
<asp:Panel ID="pnlEmpty" runat="server" CssClass="empty-state" Visible="false"><h2>No Trips need assignment</h2><p>Choose another date or review the Schedule list.</p></asp:Panel><div class="form-actions"><asp:Button ID="btnConfirm" runat="server" CssClass="btn btn-primary" Text="Confirm selected assignments" OnClick="btnConfirm_Click"/></div></section>
</asp:Content>
