using System;using System.Collections.Generic;using System.Globalization;using System.Linq;using System.Web.UI.WebControls;using ForteMove.Models.Assignments;using ForteMove.Web.Infrastructure;
namespace ForteMove.Web.Admin.Assignments
{
    public partial class AssignmentQueue:AdminPage
    {
        protected void Page_Load(object sender,EventArgs e){if(!IsPostBack){txtDate.Text=DateTime.Today.ToString("yyyy-MM-dd");Bind();}}
        protected void btnLoad_Click(object sender,EventArgs e){Bind();}
        private void Bind(){DateTime date;if(!DateTime.TryParseExact(txtDate.Text,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out date)){Show("Enter a valid service date.",true);return;}AssignmentQueueResult result=ServiceFactory.CreateAssignmentService().GetAssignmentQueue(new AssignmentQueueQuery{ServiceDate=date});rptRecommendations.DataSource=result.Recommendations;rptRecommendations.DataBind();rptReview.DataSource=result.ReviewTrips;rptReview.DataBind();pnlReview.Visible=result.ReviewTrips.Count>0;pnlEmpty.Visible=result.Recommendations.Count==0;btnConfirm.Visible=result.Recommendations.Any(item=>item.HasRecommendation);litEvaluated.Text="Evaluated "+result.EvaluatedAtLocal.ToString("g",CultureInfo.CurrentCulture)+" South African time.";}
        protected void btnConfirm_Click(object sender,EventArgs e){ConfirmAssignmentsRequest request=new ConfirmAssignmentsRequest();foreach(RepeaterItem row in rptRecommendations.Items){CheckBox selected=(CheckBox)row.FindControl("chkSelect");if(selected==null||!selected.Checked)continue;request.Items.Add(new ConfirmAssignmentItem{TripId=Long(row,"hidTripId"),BusId=Long(row,"hidBusId"),DriverProfileId=Long(row,"hidDriverId"),TripRowVersion=Bytes(row,"hidTripRv"),BusRowVersion=Bytes(row,"hidBusRv"),DriverRowVersion=Bytes(row,"hidDriverRv"),UserRowVersion=Bytes(row,"hidUserRv"),StaffRowVersion=Bytes(row,"hidStaffRv"),DecisionType=AssignmentDecisionType.RecommendationAccepted});}var result=ServiceFactory.CreateAssignmentService().ConfirmAssignments(request,CurrentPrincipalContext.UserAccountId);if(!result.Succeeded){Show(string.Join(" ",result.Errors.Select(error=>error.Message)),true);Bind();return;}Show(result.Value.AssignmentCount+" assignment(s) confirmed.",false);Bind();}
        protected string B64(object value){byte[] bytes=value as byte[];return bytes==null?string.Empty:Convert.ToBase64String(bytes);}private static long Long(RepeaterItem row,string id){long value;long.TryParse(((HiddenField)row.FindControl(id)).Value,out value);return value;}private static byte[] Bytes(RepeaterItem row,string id){try{return Convert.FromBase64String(((HiddenField)row.FindControl(id)).Value);}catch{return null;}}private void Show(string text,bool error){pnlMessage.CssClass=error?"alert alert-danger":"alert alert-success";litMessage.Text=Server.HtmlEncode(text);pnlMessage.Visible=true;}
        protected string RecommendationValue(object item,string field){AssignmentRecommendation recommendation=item as AssignmentRecommendation;if(recommendation==null)return string.Empty;switch(field){case "TripId":return recommendation.Trip.TripId.ToString(CultureInfo.InvariantCulture);case "BusId":return recommendation.Bus==null?string.Empty:recommendation.Bus.BusId.ToString(CultureInfo.InvariantCulture);case "DriverId":return recommendation.Driver==null?string.Empty:recommendation.Driver.DriverProfileId.ToString(CultureInfo.InvariantCulture);case "TripRv":return B64(recommendation.Trip.RowVersion);case "BusRv":return recommendation.Bus==null?string.Empty:B64(recommendation.Bus.RowVersion);case "DriverRv":return recommendation.Driver==null?string.Empty:B64(recommendation.Driver.DriverRowVersion);case "UserRv":return recommendation.Driver==null?string.Empty:B64(recommendation.Driver.UserRowVersion);case "StaffRv":return recommendation.Driver==null?string.Empty:B64(recommendation.Driver.StaffRowVersion);default:return string.Empty;}}protected string RecommendationLabel(object item){AssignmentRecommendation recommendation=item as AssignmentRecommendation;return recommendation==null||!recommendation.HasRecommendation?string.Empty:recommendation.Driver.EmployeeNumber+" · "+recommendation.Driver.DriverName+" · "+recommendation.Bus.FleetNumber;}
    }
}
