using System;using System.Globalization;using System.Linq;using System.Web.UI.WebControls;using ForteMove.Models.Assignments;using ForteMove.Models.Scheduling;using ForteMove.Web.Infrastructure;
namespace ForteMove.Web.Admin.Assignments
{
    public partial class AssignmentDetailsPage:AdminPage
    {
        private long Id{get{long value;return long.TryParse(Request.QueryString["id"],out value)?value:0;}}
        protected void Page_Load(object sender,EventArgs e){if(!IsPostBack)Bind();}
        private void Bind(){AssignmentDetails details=ServiceFactory.CreateAssignmentService().GetDetails(Id);if(details==null){Response.Redirect(ResolveUrl("~/Admin/Scheduling/TripList.aspx"),true);return;}litTripCode.Text=Server.HtmlEncode(details.Trip.TripCode);litTripContext.Text=Server.HtmlEncode(details.Trip.RouteCode+" · "+details.Trip.ServiceDate.ToString("d",CultureInfo.CurrentCulture)+" · "+details.Trip.ScheduledDepartureTime.ToString("hh\\:mm")+"–"+details.Trip.ExpectedFinishLocal.ToString("g",CultureInfo.CurrentCulture));hidTripRv.Value=Convert.ToBase64String(details.Trip.RowVersion);pnlReview.Visible=details.Trip.RequiresReview;pnlCurrent.Visible=details.CurrentAssignment!=null;pnlUnassigned.Visible=details.CurrentAssignment==null;btnAssign.Visible=details.CurrentAssignment==null&&details.Trip.Status==TripStatus.Unassigned;bool mutable=details.CurrentAssignment!=null&&!details.HasStarted&&(details.Trip.Status==TripStatus.Scheduled||details.Trip.Status==TripStatus.Ready||details.Trip.Status==TripStatus.Delayed);btnChange.Visible=mutable;btnRemove.Visible=mutable;btnResolve.Visible=details.Trip.RequiresReview;btnCancelTrip.Visible=details.Trip.Status!=TripStatus.Completed&&details.Trip.Status!=TripStatus.Cancelled;if(details.CurrentAssignment!=null){litCurrentDriver.Text=Server.HtmlEncode(details.CurrentAssignment.EmployeeNumber+" · "+details.CurrentAssignment.DriverName);litCurrentBus.Text=Server.HtmlEncode(details.CurrentAssignment.FleetNumber+(details.HasCurrentReadiness?" · readiness will be invalidated if changed":""));hidAssignmentRv.Value=Convert.ToBase64String(details.CurrentAssignment.RowVersion);}else hidAssignmentRv.Value=string.Empty;var alternatives=ServiceFactory.CreateAssignmentService().GetEligibleAlternatives(Id).Where(item=>details.CurrentAssignment==null||item.Bus.BusId!=details.CurrentAssignment.BusId||item.Driver.DriverProfileId!=details.CurrentAssignment.DriverProfileId).Select(item=>new{Value=item.Bus.BusId+":"+item.Driver.DriverProfileId,Text=item.Bus.FleetNumber+" · "+item.Driver.EmployeeNumber+" · "+item.Driver.DriverName}).ToList();ddlAlternative.DataSource=alternatives;ddlAlternative.DataTextField="Text";ddlAlternative.DataValueField="Value";ddlAlternative.DataBind();ddlAlternative.Items.Insert(0,new ListItem("Select an eligible pair",string.Empty));rptHistory.DataSource=details.History;rptHistory.DataBind();pnlNoHistory.Visible=details.History.Count==0;}
        protected void btnAssign_Click(object sender,EventArgs e){long bus,driver;if(!Pair(out bus,out driver)){Show("Select an eligible Driver and bus pair.",true);return;}var alternative=ServiceFactory.CreateAssignmentService().GetEligibleAlternatives(Id).FirstOrDefault(item=>item.Bus.BusId==bus&&item.Driver.DriverProfileId==driver);if(alternative==null){Show("That pair is no longer eligible.",true);Bind();return;}ConfirmAssignmentsRequest request=new ConfirmAssignmentsRequest();request.Items.Add(new ConfirmAssignmentItem{TripId=Id,BusId=bus,DriverProfileId=driver,TripRowVersion=Parse(hidTripRv.Value),BusRowVersion=alternative.Bus.RowVersion,DriverRowVersion=alternative.Driver.DriverRowVersion,UserRowVersion=alternative.Driver.UserRowVersion,StaffRowVersion=alternative.Driver.StaffRowVersion,DecisionType=AssignmentDecisionType.AlternativeSelected,Reason=txtReason.Text});var result=ServiceFactory.CreateAssignmentService().ConfirmAssignments(request,CurrentPrincipalContext.UserAccountId);Show(result.Succeeded?"Assignment confirmed.":string.Join(" ",result.Errors.Select(error=>error.Message)),!result.Succeeded);Bind();}
        protected void btnChange_Click(object sender,EventArgs e){long bus,driver;if(!Pair(out bus,out driver)){Show("Select an eligible replacement pair.",true);return;}var result=ServiceFactory.CreateAssignmentService().ChangeAssignment(new AssignmentMutationRequest{TripId=Id,BusId=bus,DriverProfileId=driver,Reason=txtReason.Text,TripRowVersion=Parse(hidTripRv.Value),AssignmentRowVersion=Parse(hidAssignmentRv.Value)},CurrentPrincipalContext.UserAccountId);Show(result.Succeeded?"Assignment changed.":string.Join(" ",result.Errors.Select(error=>error.Message)),!result.Succeeded);Bind();}
        protected void btnRemove_Click(object sender,EventArgs e){var result=ServiceFactory.CreateAssignmentService().RemoveAssignment(new AssignmentMutationRequest{TripId=Id,Reason=txtReason.Text,TripRowVersion=Parse(hidTripRv.Value),AssignmentRowVersion=Parse(hidAssignmentRv.Value)},CurrentPrincipalContext.UserAccountId);Show(result.Succeeded?"Assignment removed.":string.Join(" ",result.Errors.Select(error=>error.Message)),!result.Succeeded);Bind();}
        protected void btnResolve_Click(object sender,EventArgs e){var result=ServiceFactory.CreateAssignmentService().ResolveReview(Id,Parse(hidTripRv.Value),txtReason.Text,CurrentPrincipalContext.UserAccountId);Show(result.Succeeded?"Review completed.":string.Join(" ",result.Errors.Select(error=>error.Message)),!result.Succeeded);Bind();}
        protected void btnCancelTrip_Click(object sender,EventArgs e){var result=ServiceFactory.CreateOperationsAdminService().CancelTrip(new ForteMove.Models.Operations.CancelTripRequest{TripId=Id,Reason=txtReason.Text,TripRowVersion=Parse(hidTripRv.Value),AssignmentRowVersion=Parse(hidAssignmentRv.Value)},CurrentPrincipalContext.UserAccountId);Show(result.Succeeded?"Trip cancelled.":string.Join(" ",result.Errors.Select(error=>error.Message)),!result.Succeeded);Bind();}
        protected string FormatHistory(object item){AssignmentHistoryItem history=item as AssignmentHistoryItem;if(history==null)return string.Empty;if(history.IsCurrent)return "Current assignment";return (history.EndType.HasValue?history.EndType.Value.ToString():"Ended")+(string.IsNullOrWhiteSpace(history.EndReason)?string.Empty:": "+history.EndReason);}private bool Pair(out long bus,out long driver){bus=0;driver=0;string[] parts=(ddlAlternative.SelectedValue??string.Empty).Split(':');return parts.Length==2&&long.TryParse(parts[0],out bus)&&long.TryParse(parts[1],out driver);}private static byte[] Parse(string value){try{return Convert.FromBase64String(value);}catch{return null;}}private void Show(string text,bool error){pnlMessage.CssClass=error?"alert alert-danger":"alert alert-success";litMessage.Text=Server.HtmlEncode(text);pnlMessage.Visible=true;}
    }
}
