using System;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using ForteMove.Data.Repositories;
using ForteMove.Business.Exceptions;
using ForteMove.Business.Maintenance;
using ForteMove.Models.Maintenance;
using ForteMove.Models.Fleet;
internal static class Slice9RollbackVerification
{
 const string Connection=@"Data Source=.\SQLEXPRESS;Initial Catalog=ForteMove;Integrated Security=True;Application Name=ForteMove.Slice9Rollback";
 static SqlConnection C;static SqlTransaction Tx;static long Bus,Actor,Driver,Trip,Provider,PlanId,OrderId,Defect;static int checks;
 static DateTime Now=DateTime.UtcNow.AddHours(2),Utc=DateTime.UtcNow;
 public static int Main(){try{using(C=new SqlConnection(Connection)){C.Open();long before=Number("SELECT (SELECT COUNT(*) FROM dbo.RepairProviders)+(SELECT COUNT(*) FROM dbo.MaintenancePlans)+(SELECT COUNT(*) FROM dbo.MaintenanceWorkOrders)+(SELECT COUNT(*) FROM dbo.MaintenanceProgressEntries)+(SELECT COUNT(*) FROM dbo.BusVehicleStatusHistory);");using(Tx=C.BeginTransaction(IsolationLevel.Serializable)){try{Run();}finally{Tx.Rollback();}}Tx=null;Check(before==Number("SELECT (SELECT COUNT(*) FROM dbo.RepairProviders)+(SELECT COUNT(*) FROM dbo.MaintenancePlans)+(SELECT COUNT(*) FROM dbo.MaintenanceWorkOrders)+(SELECT COUNT(*) FROM dbo.MaintenanceProgressEntries)+(SELECT COUNT(*) FROM dbo.BusVehicleStatusHistory);"),"All maintenance fixtures rolled back");}Console.WriteLine(checks+" Slice 9 rollback checks passed; no test rows remain (identity/rowversion counters may advance).");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
 static void Run(){
 Call("ForteMove.Data.Internal.SqlFuelLifecycle","AcquireAssignmentLock",C,Tx);Call("ForteMove.Data.Internal.SqlFuelLifecycle","AcquireLock",C,Tx);Call("ForteMove.Data.Internal.SqlMaintenanceLifecycle","AcquireLock",C,Tx);
 using(var cmd=Command(@"SELECT TOP(1) a.BusId,t.TripId,a.DriverProfileId,(SELECT MIN(u.UserAccountId) FROM dbo.UserAccounts u JOIN dbo.Roles r ON r.RoleId=u.RoleId WHERE r.RoleCode=N'TransportAdministrator' AND u.IsActive=1 AND u.MustChangePassword=0)
 FROM dbo.Trips t JOIN dbo.TripAssignments a ON a.TripId=t.TripId AND a.IsCurrent=1 WHERE t.TripStatus=N'Scheduled' AND NOT EXISTS(SELECT 1 FROM dbo.TripExecutions e WHERE e.TripId=t.TripId) ORDER BY t.TripId;"))
 using(var r=cmd.ExecuteReader()){if(!r.Read())throw new Exception("Requires an existing unstarted assigned Trip.");Bus=r.GetInt64(0);Trip=r.GetInt64(1);Driver=r.GetInt64(2);Actor=r.GetInt64(3);}
 Call("ForteMove.Data.Internal.SqlMaintenanceLifecycle","Authorise",C,Tx,Actor);Expect(()=>Call("ForteMove.Data.Internal.SqlMaintenanceLifecycle","Authorise",C,Tx,0L),"Anonymous write denied");long driverUser=Number("SELECT s.UserAccountId FROM dbo.DriverProfiles d JOIN dbo.StaffProfiles s ON s.StaffProfileId=d.StaffProfileId WHERE d.DriverProfileId=@Id;",Driver);Expect(()=>Call("ForteMove.Data.Internal.SqlMaintenanceLifecycle","Authorise",C,Tx,driverUser),"Driver maintenance write denied");
 Execute("UPDATE dbo.Buses SET BaseOperationalState=N'Operational',GrossVehicleMassKg=8000,LicenceExpiryDate='20990101',RoadworthyExpiryDate='20990101',InsuranceExpiryDate='20990101' WHERE BusId=@Id;",Bus);
 Execute("UPDATE dbo.BusDefectReports SET DefectStatus=N'Resolved',ResolvedUtc=@Utc,ResolvedByUserAccountId=@Actor,ResolutionNote=N'Rollback-only safety preparation' WHERE BusId=@Id AND DefectStatus<>N'Resolved';",Bus);
 Provider=(long)Call(typeof(SqlRepairProviderRepository).FullName,"SaveInTransaction",C,Tx,new SaveRepairProviderRequest{ProviderName="ROLLBACK ONLY",AreaDescription="Synthetic verification only",IsActive=true},Actor,Utc);
 var provider=(RepairProvider)Call(typeof(SqlRepairProviderRepository).FullName,"Read",C,Tx,Provider);Check(provider.ProviderCode.StartsWith("RP-"),"Provider generated code");var updated=new SaveRepairProviderRequest{RepairProviderId=Provider,ProviderName=provider.ProviderName,AreaDescription=provider.AreaDescription,RowVersion=new byte[8],IsActive=true};Expect(()=>Call(typeof(SqlRepairProviderRepository).FullName,"SaveInTransaction",C,Tx,updated,Actor,Utc),"Stale provider denied");
 decimal odo=Safety().Bus.OdometerKilometres;var p=new SaveMaintenancePlanRequest{BusId=Bus,ServiceName="ROLLBACK ONLY",IntervalDays=30,IntervalKilometres=100,NextDueDate=Now.Date.AddDays(-1),NextDueOdometer=odo,IsActive=true,BlocksOperationWhenOverdue=true};
 PlanId=(long)Call("SavePlanInTransaction",C,Tx,p,Actor,Now,Utc);Check(Plan().PlanCode.StartsWith("MP-")&&!Plan().LastServiceDate.HasValue,"Explicit first due leaves service history empty");
 Expect(()=>Call("ForteMove.Data.Internal.SqlMaintenanceLifecycle","EnsureNewOperation",C,Tx,Bus,Now),"Locked overdue safety guard");Expect(()=>Call("ForteMove.Data.Internal.SqlMaintenanceLifecycle","EnsureDriverDeparture",C,Tx,Trip,driverUser,Now),"Driver readiness/start overdue guard");
 Execute(@"INSERT dbo.BusDefectReports(DefectCode,BusId,ReportedByDriverProfileId,Category,Severity,Description,DefectStatus,ReportedUtc,UpdatedUtc)
 VALUES(N'DF-S9-ROLLBACK',@Id,@Other,N'Other',N'Critical',N'Rollback only',N'Open',@Utc,@Utc);",Bus,Driver);Defect=Number("SELECT BusDefectReportId FROM dbo.BusDefectReports WHERE DefectCode=N'DF-S9-ROLLBACK';");
 var request=new CreateWorkOrderRequest{BusId=Bus,RepairProviderId=Provider,MaintenanceType=MaintenanceType.Corrective,TriggerType=MaintenanceTrigger.Defect,BusDefectReportId=Defect,MaintenancePlanId=PlanId,RequestedWork="Rollback only",CreationToken=Guid.NewGuid()};
 Expect(()=>Call("CreateInTransaction",C,Tx,request,Actor,Now,Utc),"Open defect requires review note");
 request.DefectReviewNote="Verified rollback review";request.DefectRowVersion=(byte[])Scalar("SELECT RowVersion FROM dbo.BusDefectReports WHERE BusDefectReportId=@Id;",Defect);
 OrderId=(long)Call("CreateInTransaction",C,Tx,request,Actor,Now,Utc);
 Expect(()=>Execute(@"INSERT dbo.MaintenanceWorkOrders(WorkOrderCode,CreationToken,BusId,RepairProviderId,ProviderCodeSnapshot,ProviderNameSnapshot,MaintenanceType,TriggerType,RequestedWork,OrderStatus,OpenedUtc,CreatedByUserAccountId,UpdatedByUserAccountId,UpdatedUtc)
SELECT N'MWO-NULL-CHECK',NEWID(),BusId,RepairProviderId,ProviderCodeSnapshot,ProviderNameSnapshot,N'Corrective',N'ComplianceExpiry',N'Constraint fixture',N'Open',@Utc,@Actor,@Actor,@Utc FROM dbo.MaintenanceWorkOrders WHERE MaintenanceWorkOrderId=@Id;",OrderId),"SQL rejects null compliance source");
Expect(()=>Execute(@"INSERT dbo.MaintenanceWorkOrders(WorkOrderCode,CreationToken,BusId,RepairProviderId,ProviderCodeSnapshot,ProviderNameSnapshot,MaintenanceType,TriggerType,RequestedWork,OrderStatus,OpenedUtc,CreatedByUserAccountId,UpdatedByUserAccountId,UpdatedUtc,CompletedCost)
SELECT N'MWO-METADATA-CHECK',NEWID(),BusId,RepairProviderId,ProviderCodeSnapshot,ProviderNameSnapshot,N'Corrective',N'Manual',N'Constraint fixture',N'Open',@Utc,@Actor,@Actor,@Utc,0 FROM dbo.MaintenanceWorkOrders WHERE MaintenanceWorkOrderId=@Id;",OrderId),"SQL rejects completion cost on open order");
var differentBus=Number("SELECT MIN(BusId) FROM dbo.Buses WHERE BusId<>@Id;",Bus);
var mismatched=new CreateWorkOrderRequest{BusId=differentBus,RepairProviderId=Provider,MaintenanceType=MaintenanceType.Corrective,TriggerType=MaintenanceTrigger.Defect,BusDefectReportId=Defect,RequestedWork="Rollback-only wrong Bus",CreationToken=Guid.NewGuid()};
Expect(()=>Call("CreateInTransaction",C,Tx,mismatched,Actor,Now,Utc),"Wrong-Bus defect source denied");
Expect(()=>Execute(@"DECLARE @LinkedPlan bigint=(SELECT MaintenancePlanId FROM dbo.MaintenanceWorkOrders WHERE MaintenanceWorkOrderId=@Id);
UPDATE dbo.MaintenanceWorkOrders SET MaintenancePlanId=NULL WHERE MaintenanceWorkOrderId=@Id;
INSERT dbo.MaintenanceWorkOrders(WorkOrderCode,CreationToken,BusId,RepairProviderId,ProviderCodeSnapshot,ProviderNameSnapshot,MaintenanceType,TriggerType,RequestedWork,OrderStatus,OpenedUtc,CreatedByUserAccountId,UpdatedByUserAccountId,UpdatedUtc,MaintenancePlanId)
SELECT N'MWO-CONTEXT-CHECK',NEWID(),@Other,RepairProviderId,ProviderCodeSnapshot,ProviderNameSnapshot,N'Preventive',N'ServiceDate',N'Constraint fixture',N'Open',@Utc,@Actor,@Actor,@Utc,@LinkedPlan FROM dbo.MaintenanceWorkOrders WHERE MaintenanceWorkOrderId=@Id;",OrderId,differentBus),"SQL same-Bus relationship enforced");
Check(Number("SELECT COUNT(*) FROM dbo.BusDefectReports WHERE BusDefectReportId=@Id AND DefectStatus=N'Reviewed';",Defect)==1,"Create reuses defect review atomically");Check(Safety().Bus.BaseOperationalState==BusOperationalState.Operational&&Order().Status==MaintenanceOrderStatus.Open,"Creation never changes vehicle status");Check((long)Call("CreateInTransaction",C,Tx,request,Actor,Now,Utc)==OrderId,"Creation replay idempotent");
 request.CreationToken=Guid.NewGuid();Expect(()=>Call("CreateInTransaction",C,Tx,request,Actor,Now,Utc),"One active order per linked source");Check(Number("SELECT COUNT(*) FROM dbo.MaintenanceWorkOrders WHERE MaintenancePlanId=@Id;",PlanId)==1,"Duplicate did not persist");
 var currentPlan=Plan();p.MaintenancePlanId=PlanId;p.RowVersion=currentPlan.RowVersion;Expect(()=>Call("SavePlanInTransaction",C,Tx,p,Actor,Now,Utc),"Plan editing blocked while linked active work");
 var start=Review();var stale=new StartMaintenanceRequest{MaintenanceWorkOrderId=OrderId,RowVersion=start.Order.RowVersion,Fingerprint="wrong"};Expect(()=>Call("StartInTransaction",C,Tx,stale,Actor,Now,Utc),"Stale start impact rejected");
 Call("StartInTransaction",C,Tx,new StartMaintenanceRequest{MaintenanceWorkOrderId=OrderId,RowVersion=start.Order.RowVersion,Fingerprint=start.Fingerprint},Actor,Now,Utc);
 Check(Order().Status==MaintenanceOrderStatus.InProgress&&Safety().Bus.BaseOperationalState==BusOperationalState.UnderMaintenance,"Start and vehicle status atomic");Check(Number("SELECT COUNT(*) FROM dbo.Trips WHERE TripId=@Id AND RequiresReview=1;",Trip)==1,"Assigned unstarted Trip retained for review");Check(Number("SELECT COUNT(*) FROM dbo.TripAssignments WHERE TripId=@Id AND IsCurrent=1;",Trip)==1,"Assignment retained");Check(Number("SELECT COUNT(*) FROM dbo.FuelTransactions WHERE BusId=@Id;",Bus)==0,"Maintenance creates no fuel transaction");
 Expect(()=>Call("StartInTransaction",C,Tx,stale,Actor,Now,Utc),"Duplicate start denied");
 Call("ProgressInTransaction",C,Tx,new MaintenanceActionRequest{MaintenanceWorkOrderId=OrderId,RowVersion=Order().RowVersion,Note="Verified progress"},Actor,Utc);
 Check(Number("SELECT COUNT(*) FROM dbo.MaintenanceProgressEntries WHERE MaintenanceWorkOrderId=@Id;",OrderId)==1,"Append-only progress");var complete=Completion(odo-1);Expect(()=>Call("CompleteInTransaction",C,Tx,complete,Actor,Now,Utc),"Decreasing service reading denied");complete=Completion(odo+1);complete.BusRowVersion=new byte[8];Expect(()=>Call("CompleteInTransaction",C,Tx,complete,Actor,Now,Utc),"Stale completion bus denied");
 complete=Completion(odo+1);Call("CompleteInTransaction",C,Tx,complete,Actor,Now,Utc);
 Check(Order().Status==MaintenanceOrderStatus.Completed&&Safety().Bus.BaseOperationalState==BusOperationalState.UnderMaintenance,"Completion leaves bus in workshop");Check(Safety().Bus.OdometerKilometres==odo+1,"Verified odometer advances atomically");Check(Plan().LastServiceDate==Now.Date&&Plan().LastServiceOdometer==odo+1&&Plan().NextDueOdometer==odo+101,"Plan reset only from completion");Check(Number("SELECT COUNT(*) FROM dbo.BusDefectReports WHERE BusDefectReportId=@Id AND DefectStatus=N'Reviewed';",Defect)==1,"No implicit defect resolution");
 Expect(()=>Call("CompleteInTransaction",C,Tx,complete,Actor,Now,Utc),"Terminal completion immutable");Expect(()=>Call("CancelInTransaction",C,Tx,new MaintenanceActionRequest{MaintenanceWorkOrderId=OrderId,RowVersion=Order().RowVersion,Note="Terminal test"},Actor,Utc),"Completed order cannot cancel");
 Expect(()=>Return(),"Critical blocks return");Call("ForteMove.Data.Internal.SqlDefectLifecycle","Update",C,Tx,new ForteMove.Models.Operations.UpdateDefectRequest{BusDefectReportId=Defect,RowVersion=(byte[])Scalar("SELECT RowVersion FROM dbo.BusDefectReports WHERE BusDefectReportId=@Id;",Defect),Note="Verified resolution"},Actor,Utc,true);Return();Check(Safety().Bus.BaseOperationalState==BusOperationalState.Operational,"Deliberate return only after safety");Check(Number("SELECT COUNT(*) FROM dbo.Trips WHERE TripId=@Id AND RequiresReview=1;",Trip)==1,"Return does not clear review flags");
 Check(Number("SELECT COUNT(*) FROM dbo.BusVehicleStatusHistory WHERE BusId=@Id;",Bus)>=2,"Genuine status history");
 var manual=new CreateWorkOrderRequest{BusId=Bus,RepairProviderId=Provider,MaintenanceType=MaintenanceType.Breakdown,TriggerType=MaintenanceTrigger.Manual,RequestedWork="External need, rollback only",CreationToken=Guid.NewGuid()};
 OrderId=(long)Call("CreateInTransaction",C,Tx,manual,Actor,Now,Utc);Call("CancelInTransaction",C,Tx,new MaintenanceActionRequest{MaintenanceWorkOrderId=OrderId,RowVersion=Order().RowVersion,Note="Verified open cancellation"},Actor,Utc);Check(Safety().Bus.BaseOperationalState==BusOperationalState.Operational,"Open cancellation leaves status unchanged");
 manual.CreationToken=Guid.NewGuid();OrderId=(long)Call("CreateInTransaction",C,Tx,manual,Actor,Now,Utc);start=Review();Call("StartInTransaction",C,Tx,new StartMaintenanceRequest{MaintenanceWorkOrderId=OrderId,RowVersion=start.Order.RowVersion,Fingerprint=start.Fingerprint},Actor,Now,Utc);Call("CancelInTransaction",C,Tx,new MaintenanceActionRequest{MaintenanceWorkOrderId=OrderId,RowVersion=Order().RowVersion,Note="Verified workshop cancellation"},Actor,Utc);Check(Safety().Bus.BaseOperationalState==BusOperationalState.UnderMaintenance,"InProgress cancellation leaves unavailable status");
 Check(Number("SELECT COUNT(*) FROM sys.check_constraints WHERE parent_object_id IN(OBJECT_ID(N'dbo.MaintenancePlans'),OBJECT_ID(N'dbo.RepairProviders'),OBJECT_ID(N'dbo.MaintenanceWorkOrders'),OBJECT_ID(N'dbo.MaintenanceProgressEntries'),OBJECT_ID(N'dbo.BusVehicleStatusHistory')) AND (is_disabled=1 OR is_not_trusted=1);")==0,"Maintenance checks trusted");
 }
 static CompleteMaintenanceRequest Completion(decimal odo){var w=Order();return new CompleteMaintenanceRequest{MaintenanceWorkOrderId=OrderId,RowVersion=w.RowVersion,BusRowVersion=w.BusRowVersion,PlanRowVersion=w.PlanRowVersion,ServiceOdometer=odo,WorkPerformed="Verified work",Note="Verified completion"};}
 static void Return(){Call("ReturnInTransaction",C,Tx,new ReturnToServiceRequest{BusId=Bus,BusRowVersion=Safety().Bus.RowVersion,Note="Verified safety decision"},Actor,Now,Utc);}
 static BusSafetyContext Safety(){return (BusSafetyContext)Call("ForteMove.Data.Internal.SqlMaintenanceLifecycle","ReadSafety",C,Tx,Bus);}
 static MaintenanceWorkOrder Order(){return (MaintenanceWorkOrder)Call("ReadOrder",C,Tx,OrderId);}
 static MaintenancePlan Plan(){return (MaintenancePlan)Call("ReadPlan",C,Tx,PlanId);}
 static MaintenanceStartReview Review(){return (MaintenanceStartReview)Call("ReadStartReview",C,Tx,OrderId);}
 static object Call(string name,params object[] args){return Call(typeof(SqlMaintenanceRepository).FullName,name,args);}
 static object Call(string type,string name,params object[] args){try{return typeof(SqlMaintenanceRepository).Assembly.GetType(type,true).GetMethod(name,BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,args);}catch(TargetInvocationException e){throw e.InnerException;}}
 static void Expect(Action a,string label){Tx.Save("ExpectedFailure");bool fail=false;try{a();}catch(MaintenancePersistenceException){fail=true;}catch(ForteMove.Business.Exceptions.TripOperationsPersistenceException){fail=true;}catch(SqlException){fail=true;}Tx.Rollback("ExpectedFailure");Check(fail,label);}
 static SqlCommand Command(string sql){return new SqlCommand(sql,C,Tx);}
 static object Scalar(string sql,long id=0){using(var cmd=Command(sql)){cmd.Parameters.Add("@Id",SqlDbType.BigInt).Value=id;return cmd.ExecuteScalar();}}
 static long Number(string sql,long id=0){return Convert.ToInt64(Scalar(sql,id));}
 static void Execute(string sql,long id=0,long other=0){using(var cmd=Command(sql)){cmd.Parameters.Add("@Id",SqlDbType.BigInt).Value=id;cmd.Parameters.Add("@Other",SqlDbType.BigInt).Value=other;cmd.Parameters.Add("@Actor",SqlDbType.BigInt).Value=Actor;cmd.Parameters.Add("@Utc",SqlDbType.DateTime2).Value=Utc;cmd.ExecuteNonQuery();}}
 static void Check(bool x,string label){if(!x)throw new Exception(label);checks++;}
}
