using System;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using ForteMove.Business.Time;
using ForteMove.Business.Services;
using ForteMove.Business.Exceptions;
using ForteMove.Business.Fuel;
using ForteMove.Data.Repositories;
using ForteMove.Models.Maintenance;
using ForteMove.Models.Fuel;
using ForteMove.Models.Operations;
using ForteMove.Models.Fleet;
using ForteMove.Models.Passengers;
using ForteMove.Models.Assignments;
internal static class Slice9ConcurrencyVerification
{
 static string Connection;static int checks;static Clock clock=new Clock();
 static SqlMaintenanceRepository M(){return new SqlMaintenanceRepository(Connection,clock);}
 static SqlTripOperationsRepository O(){return new SqlTripOperationsRepository(Connection,clock);}
 static SqlFuelRepository F(){return new SqlFuelRepository(Connection);}
 static DateTime Now{get{return clock.OperationalNow;}}static DateTime Utc{get{return clock.UtcNow;}}
 public static int Main(string[] args){try{
 if(args.Length!=1||!System.Text.RegularExpressions.Regex.IsMatch(args[0],"^ForteMove_Slice9_Verification_[a-f0-9]{32}$"))throw new Exception("Use the runner-owned disposable database only.");
 Connection=@"Data Source=.\SQLEXPRESS;Integrated Security=True;Initial Catalog="+args[0];
 Check(Number("SELECT COUNT(*) FROM dbo.UserAccounts;")==0,"Disposable schema empty");
 Execute((string)typeof(Slice8ConcurrencyVerification).GetField("Fixture",BindingFlags.NonPublic|BindingFlags.Static).GetRawConstantValue());
 clock.Value=DateTime.UtcNow.AddHours(2).Date.AddDays(1).AddHours(8).AddMinutes(55);
 var providers=new SqlRepairProviderRepository(Connection,clock);long provider=providers.SaveProvider(new SaveRepairProviderRequest{ProviderName="Synthetic provider",AreaDescription="Disposable verification only",IsActive=true},1);
 Execute(@"INSERT dbo.PassengerProfiles(UserAccountId,FirstName,LastName,CreatedUtc,UpdatedUtc) VALUES(4,N'Synthetic',N'Passenger',SYSUTCDATETIME(),SYSUTCDATETIME());
INSERT dbo.PassengerWallets(PassengerProfileId,CurrentBalance,CreatedUtc,UpdatedUtc) VALUES(1,100,SYSUTCDATETIME(),SYSUTCDATETIME());");
 var passenger=new PassengerService(new SqlPassengerRepository(Connection,clock),clock);var journey=passenger.GetJourneyDetails(4,7,Guid.NewGuid()).Value;Check(journey.CanPurchase,"Assigned future Trip sale baseline");var purchase=Purchase(journey);Check(passenger.PurchaseTicket(4,purchase).Succeeded,"Production purchase before maintenance");
 var plan=new SaveMaintenancePlanRequest{BusId=1,ServiceName="Synthetic service",IntervalDays=30,NextDueDate=Now.Date.AddDays(-1),IsActive=true,BlocksOperationWhenOverdue=true};long planId=M().SavePlan(plan,1);
 Check(!passenger.GetJourneyDetails(4,8,Guid.NewGuid()).Value.CanPurchase,"Overdue passenger preview unavailable");var trip=O().GetDriverTripDetails(2,1,Now);Expect(()=>O().ConfirmReadiness(Readiness(trip),2,Now,Utc),"Locked overdue readiness rejection");Expect(()=>O().StartTrip(Action(trip),2,Now,Utc),"Locked overdue start rejection");Check(new AssignmentService(new SqlAssignmentRepository(Connection,clock),clock).GetEligibleAlternatives(2).Count==0,"Overdue alternatives excluded");
 var ticketBefore=Number("SELECT COUNT(*) FROM dbo.Tickets WHERE TicketStatus=N'Purchased';");Check(ticketBefore==1&&Number("SELECT COUNT(*) FROM dbo.WalletTransactions WHERE TransactionType=N'TripCancellationRefund';")==0,"Overdue never refunds");
 var stored=M().GetPlan(planId);plan.MaintenancePlanId=planId;plan.RowVersion=stored.RowVersion;plan.NextDueDate=Now.Date;M().SavePlan(plan,1);
 var d=O().GetDriverTripDetails(2,3,Now);long defect=O().ReportDefect(new ReportDefectRequest{TripId=3,TripRowVersion=d.TripRowVersion,AssignmentRowVersion=d.AssignmentRowVersion,Category=DefectCategory.Other,Severity=DefectSeverity.Major,Description="Disposable linked issue"},2,Now,Utc).BusDefectReportId;
 var def=O().GetDefectDetails(defect);
 var request=new CreateWorkOrderRequest{BusId=1,RepairProviderId=provider,MaintenanceType=MaintenanceType.Corrective,TriggerType=MaintenanceTrigger.Defect,MaintenancePlanId=planId,BusDefectReportId=defect,DefectRowVersion=def.RowVersion,DefectReviewNote="Synthetic review",RequestedWork="Synthetic work",CreationToken=Guid.NewGuid()};
 var creates=Race(()=>M().CreateWorkOrder(request,1),()=>M().CreateWorkOrder(request,1));Check(creates.All(x=>x.Error==null)&&creates.Select(x=>x.Value).Distinct().Count()==1,"Concurrent duplicate confirmation idempotent");long order=(long)creates[0].Value;Check(Number("SELECT COUNT(*) FROM dbo.MaintenanceWorkOrders;")==1,"One committed order");
 Expect(()=>M().CreateWorkOrder(new CreateWorkOrderRequest{BusId=1,RepairProviderId=provider,MaintenanceType=MaintenanceType.Preventive,TriggerType=MaintenanceTrigger.ServiceDate,MaintenancePlanId=planId,RequestedWork="Duplicate plan",CreationToken=Guid.NewGuid()},1),"Duplicate linked active order rejected");
 // Live unused fuel authorizations and an immutable redeemed history record.
 long station=new SqlFuelStationRepository(Connection).Save(new SaveFuelStationRequest{StationName="Synthetic",AreaDescription="Disposable only",IsActive=true,SupportsDiesel=true},1,Utc);
 var active=Voucher(2,station);var redeemed=Voucher(4,station);var vs=F().GetVoucher(redeemed.Id,1,false);var stationRow=new SqlFuelStationRepository(Connection).GetStation(station,1);F().Redeem(new RedeemFuelVoucherRequest{Token=redeemed.Token,FuelStationId=station,VoucherRowVersion=vs.RowVersion,StationRowVersion=stationRow.RowVersion,PreviewFingerprint=FuelPolicy.Fingerprint(vs,stationRow)},FuelRedemptionToken.Hash(redeemed.Token),1,Now,Utc);
 var fuel3=F().GetDriverTrip(3,2);long pending=F().Submit(new SubmitFuelRequest{TripId=3,TripRowVersion=fuel3.TripRowVersion,AssignmentRowVersion=fuel3.AssignmentRowVersion,SubmissionToken=Guid.NewGuid(),Justification="Synthetic pending"},2,Now,Utc).FuelRequestId;
 trip=O().GetDriverTripDetails(2,1,Now);O().ConfirmReadiness(Readiness(trip),2,Now,Utc);trip=O().GetDriverTripDetails(2,1,Now);var review=M().PreviewStart(order);var start=new StartMaintenanceRequest{MaintenanceWorkOrderId=order,RowVersion=review.Order.RowVersion,Fingerprint=review.Fingerprint};
 var starting=Race(()=>{M().StartMaintenance(start,1);return true;},()=>{O().StartTrip(Action(trip),2,Now,Utc);return true;});
 Check(starting.Count(x=>x.Error==null)==1,"Trip start versus maintenance: exactly one winner");
 if(starting[1].Error==null){Check(M().GetWorkOrder(order).Status==MaintenanceOrderStatus.Open,"Active execution prevents workshop entry");var current=O().GetDriverTripDetails(2,1,Now);O().CancelTrip(new CancelTripRequest{TripId=1,TripRowVersion=current.TripRowVersion,AssignmentRowVersion=current.AssignmentRowVersion,Reason="Synthetic breakdown cancellation"},1,Utc);var resources=new SqlAssignmentRepository(Connection,clock).GetAssignmentData(Now.Date);Check(!resources.Buses.Single().HasActiveExecution&&!resources.Drivers.Single(x=>x.DriverProfileId==1).HasActiveExecution,"Cancelled execution preserves history without occupying resources");review=M().PreviewStart(order);M().StartMaintenance(new StartMaintenanceRequest{MaintenanceWorkOrderId=order,RowVersion=review.Order.RowVersion,Fingerprint=review.Fingerprint},1);}
 Check(M().GetBusSafety(1).Bus.BaseOperationalState==BusOperationalState.UnderMaintenance,"Workshop bus unavailable");Check(F().GetRequest(pending,1,false).Status==FuelRequestStatus.Cancelled&&F().GetVoucher(active.Id,1,false).Status==FuelVoucherStatus.Cancelled,"Pending and unused active fuel cancelled");Check(F().GetVoucher(redeemed.Id,1,false).Status==FuelVoucherStatus.Redeemed&&Number("SELECT COUNT(*) FROM dbo.FuelTransactions;")==1,"Redeemed fuel history immutable");Check(Number("SELECT COUNT(*) FROM dbo.TripAssignments WHERE IsCurrent=1;")>=7&&Number("SELECT COUNT(*) FROM dbo.Trips WHERE RequiresReview=1;")>=7,"Affected assigned Trips retained and reviewed");Check(Number("SELECT COUNT(*) FROM dbo.Tickets WHERE TicketStatus=N'Purchased';")==ticketBefore,"Maintenance preserves purchased tickets");
 Check(!FuelPolicy.Eligible(F().GetDriverTrip(2,2)),"UnderMaintenance hides new fuel request");var context=F().GetDriverTrip(2,2);Expect(()=>F().Submit(new SubmitFuelRequest{TripId=2,TripRowVersion=context.TripRowVersion,AssignmentRowVersion=context.AssignmentRowVersion,SubmissionToken=Guid.NewGuid(),Justification="Must reject"},2,Now,Utc),"UnderMaintenance rejects posted request");
 var cancelledVoucher=F().GetVoucher(active.Id,1,false);
 Expect(()=>F().Redeem(new RedeemFuelVoucherRequest{Token=active.Token,FuelStationId=station,VoucherRowVersion=cancelledVoucher.RowVersion,StationRowVersion=stationRow.RowVersion,PreviewFingerprint=FuelPolicy.Fingerprint(cancelledVoucher,stationRow)},FuelRedemptionToken.Hash(active.Token),1,Now,Utc),"UnderMaintenance rejects redemption of invalidated voucher");
 var cancelledRequest=F().GetRequest(pending,1,false);
 Expect(()=>F().Approve(new ApproveFuelRequest{FuelRequestId=pending,FuelStationId=station,Quantity=1,Amount=0,ValidUntilLocal=cancelledRequest.Context.ExpectedFinishLocal.AddHours(2),RequestRowVersion=cancelledRequest.RowVersion,TripRowVersion=cancelledRequest.Context.TripRowVersion,AssignmentRowVersion=cancelledRequest.Context.AssignmentRowVersion,BusRowVersion=cancelledRequest.Context.BusRowVersion,StationRowVersion=stationRow.RowVersion},1,FuelRedemptionToken.Hash(FuelRedemptionToken.Create()),new byte[32],Now,Utc),"UnderMaintenance rejects approval of invalidated request");
 var fleet=M().GetBusSafety(1).Bus;var edit=new UpdateBusEligibilityRequest{BusId=1,BusCategoryId=fleet.BusCategoryId,PassengerCapacity=fleet.PassengerCapacity,GrossVehicleMassKg=fleet.GrossVehicleMassKg,LicenceExpiryDate=fleet.LicenceExpiryDate,RoadworthyExpiryDate=fleet.RoadworthyExpiryDate,InsuranceExpiryDate=fleet.InsuranceExpiryDate,BaseOperationalState=BusOperationalState.Operational,RowVersion=fleet.RowVersion};
 Check(!new BusService(new SqlBusRepository(Connection,clock),clock).UpdateBusEligibility(edit,1).Succeeded,"Fleet Edit cannot bypass Return workflow");
 var w=M().GetWorkOrder(order);var complete=Completion(w);complete.BusRowVersion=new byte[8];Expect(()=>M().CompleteWorkOrder(complete,1),"Stale completion rolls back");Check(M().GetWorkOrder(order).Status==MaintenanceOrderStatus.InProgress&&M().GetBusSafety(1).Bus.OdometerKilometres==100,"No partial completion");
 w=M().GetWorkOrder(order);complete=Completion(w);complete.ResolveLinkedDefect=true;complete.DefectRowVersion=w.DefectRowVersion;complete.ResolutionNote="Synthetic verified repair";var resolution=new UpdateDefectRequest{BusDefectReportId=defect,RowVersion=w.DefectRowVersion,Note="Synthetic parallel resolution"};
 var completed=Race(()=>{M().CompleteWorkOrder(complete,1);return true;},()=>{O().ResolveDefect(resolution,1,Utc);return true;});
 Check(completed.Count(x=>x.Error==null)==1,"Completion versus defect resolution is concurrency safe");
 if(completed[0].Error!=null){Check(M().GetWorkOrder(order).Status==MaintenanceOrderStatus.InProgress&&M().GetBusSafety(1).Bus.OdometerKilometres==100,"Stale linked-defect completion rolled back");M().CompleteWorkOrder(Completion(M().GetWorkOrder(order)),1);}
 Check(M().GetWorkOrder(order).Status==MaintenanceOrderStatus.Completed&&M().GetBusSafety(1).Bus.BaseOperationalState==BusOperationalState.UnderMaintenance,"Completion separate from return");Check(M().GetPlan(planId).LastServiceDate==Now.Date&&M().GetPlan(planId).NextDueDate==Now.Date.AddDays(30),"Plan reset from authoritative service date");
 var safety=M().GetBusSafety(1);var returning=new ReturnToServiceRequest{BusId=1,BusRowVersion=safety.Bus.RowVersion,Note="Synthetic safety decision"};
 // Expiry while a review is open is checked at the new authoritative operational date.
 Execute("UPDATE dbo.Buses SET LicenceExpiryDate=@Date WHERE BusId=1;",Now.Date);returning.BusRowVersion=M().GetBusSafety(1).Bus.RowVersion;clock.Value=clock.Value.AddDays(1);Expect(()=>M().ReturnToService(returning,1),"Expiry during Return review rejected");Execute("UPDATE dbo.Buses SET LicenceExpiryDate='20990101' WHERE BusId=1;");returning.BusRowVersion=M().GetBusSafety(1).Bus.RowVersion;M().ReturnToService(returning,1);Check(M().GetBusSafety(1).Bus.BaseOperationalState==BusOperationalState.Operational,"Safe explicit return");Check(Number("SELECT COUNT(*) FROM dbo.Trips WHERE RequiresReview=1;")>=7,"Trip reviews not silently cleared");
 // Keep current assignment performs real eligibility revalidation.
 var assignmentRepo=new SqlAssignmentRepository(Connection,clock);var a=assignmentRepo.GetDetails(2);assignmentRepo.ResolveReview(2,a.Trip.RowVersion,"Synthetic fresh eligibility review",1,Utc);Check(!assignmentRepo.GetDetails(2).Trip.RequiresReview,"Locked keep-current resolution");
 var detail=O().GetDriverTripDetails(2,2,Now);O().ConfirmReadiness(Readiness(detail),2,Now,Utc);detail=O().GetDriverTripDetails(2,2,Now);O().StartTrip(Action(detail),2,Now,Utc);
 var overdue=new SaveMaintenancePlanRequest{BusId=1,ServiceName="Synthetic overdue during operation",IntervalDays=1,NextDueDate=Now.Date.AddDays(-1),IsActive=true,BlocksOperationWhenOverdue=true};M().SavePlan(overdue,1);
 detail=O().GetDriverTripDetails(2,2,Now);O().ReportDelay(new ReportDelayRequest{TripId=2,TripRowVersion=detail.TripRowVersion,AssignmentRowVersion=detail.AssignmentRowVersion,Reason="Synthetic delay"},2,Now,Utc);detail=O().GetDriverTripDetails(2,2,Now);O().ResumeTrip(Action(detail),2,Now,Utc);Check(O().GetDriverTripDetails(2,2,Now).Status==ForteMove.Models.Scheduling.TripStatus.InProgress,"Overdue does not block in-trip resume");
 clock.Value=clock.Value.AddMinutes(1);detail=O().GetDriverTripDetails(2,2,Now);O().CompleteTrip(new CompleteTripRequest{TripId=2,TripRowVersion=detail.TripRowVersion,AssignmentRowVersion=detail.AssignmentRowVersion,BusRowVersion=detail.BusRowVersion,RelatedRowVersion=detail.Execution.RowVersion,EndOdometerKilometres=102},2,Now,Utc);
 Check(O().GetDriverTripDetails(2,2,Now).Status==ForteMove.Models.Scheduling.TripStatus.Completed&&M().GetBusSafety(1).Bus.OdometerKilometres==102,"Overdue permits active Trip completion and odometer advance");
 var purchaseTrip=O().GetDriverTripDetails(2,7,Now);O().CancelTrip(new CancelTripRequest{TripId=7,TripRowVersion=purchaseTrip.TripRowVersion,AssignmentRowVersion=purchaseTrip.AssignmentRowVersion,Reason="Synthetic commercial regression"},1,Utc);Check(Number("SELECT COUNT(*) FROM dbo.Tickets WHERE TicketStatus=N'Refunded';")==1&&Number("SELECT COUNT(*) FROM dbo.WalletTransactions WHERE TransactionType=N'TripCancellationRefund';")==1,"Sole cancellation refund path preserved");
 Expect(()=>M().RecordProgress(new MaintenanceActionRequest{MaintenanceWorkOrderId=order,RowVersion=M().GetWorkOrder(order).RowVersion,Note="Tampered terminal write"},2),"Driver POST repository denied");
 Expect(()=>M().RecordProgress(new MaintenanceActionRequest{MaintenanceWorkOrderId=order,RowVersion=M().GetWorkOrder(order).RowVersion,Note="Passenger tampering"},4),"Passenger POST repository denied");
 Expect(()=>M().CancelWorkOrder(new MaintenanceActionRequest{MaintenanceWorkOrderId=order,RowVersion=M().GetWorkOrder(order).RowVersion,Note="Anonymous tampering"},0),"Anonymous POST repository denied");
 var providerRow=providers.GetProvider(provider);providers.SaveProvider(new SaveRepairProviderRequest{RepairProviderId=provider,ProviderName=providerRow.ProviderName,AreaDescription=providerRow.AreaDescription,IsActive=false,RowVersion=providerRow.RowVersion},1);
 Expect(()=>M().CreateWorkOrder(new CreateWorkOrderRequest{BusId=1,RepairProviderId=provider,MaintenanceType=MaintenanceType.Corrective,TriggerType=MaintenanceTrigger.Manual,RequestedWork="Inactive selection",CreationToken=Guid.NewGuid()},1),"Inactive provider not selectable for new work");
 providerRow=providers.GetProvider(provider);providers.SaveProvider(new SaveRepairProviderRequest{RepairProviderId=provider,ProviderName=providerRow.ProviderName,AreaDescription=providerRow.AreaDescription,IsActive=true,RowVersion=providerRow.RowVersion},1);
 var manual=new CreateWorkOrderRequest{BusId=1,RepairProviderId=provider,MaintenanceType=MaintenanceType.Corrective,TriggerType=MaintenanceTrigger.Manual,RequestedWork="Disposable populated-page fixture",CreationToken=Guid.NewGuid()};
 M().CreateWorkOrder(manual,1);manual.CreationToken=Guid.NewGuid();long inProgress=M().CreateWorkOrder(manual,1);var startReview=M().PreviewStart(inProgress);M().StartMaintenance(new StartMaintenanceRequest{MaintenanceWorkOrderId=inProgress,RowVersion=startReview.Order.RowVersion,Fingerprint=startReview.Fingerprint},1);
 providerRow=providers.GetProvider(provider);providers.SaveProvider(new SaveRepairProviderRequest{RepairProviderId=provider,ProviderName=providerRow.ProviderName,AreaDescription=providerRow.AreaDescription,IsActive=false,RowVersion=providerRow.RowVersion},1);
 Check(M().GetWorkOrder(inProgress).ProviderNameSnapshot=="Synthetic provider","Inactive provider preserves approved work/history");
 Console.WriteLine(checks+" Slice 9 disposable-database concurrency/integration checks passed.");return 0;
 }catch(Exception e){Console.Error.WriteLine(e);return 1;}}
 static CompleteMaintenanceRequest Completion(MaintenanceWorkOrder w){return new CompleteMaintenanceRequest{MaintenanceWorkOrderId=w.MaintenanceWorkOrderId,RowVersion=w.RowVersion,BusRowVersion=w.BusRowVersion,PlanRowVersion=w.PlanRowVersion,ServiceOdometer=101,WorkPerformed="Synthetic verified work",Note="Synthetic completion",CompletedCost=0};}
 static ConfirmReadinessRequest Readiness(DriverTripDetails d){return new ConfirmReadinessRequest{TripId=d.TripId,TripRowVersion=d.TripRowVersion,AssignmentRowVersion=d.AssignmentRowVersion,StartOdometerKilometres=d.BusOdometerKilometres,ExteriorConditionChecked=true,TyresSafeChecked=true,LightsIndicatorsChecked=true,NoCriticalDashboardWarningsChecked=true,DoorsOperationalChecked=true,EmergencyEquipmentPresentChecked=true,NoBlockingNewDefectChecked=true};}
 static TripOperationRequest Action(DriverTripDetails d){return new TripOperationRequest{TripId=d.TripId,TripRowVersion=d.TripRowVersion,AssignmentRowVersion=d.AssignmentRowVersion,RelatedRowVersion=d.Execution==null?null:d.Execution.RowVersion};}
 static PurchaseTicketRequest Purchase(JourneyDetails d){return new PurchaseTicketRequest{TripId=d.Candidate.TripId,ReviewedFare=d.Candidate.DefaultFare,TripRowVersion=d.Candidate.TripRowVersion,RouteRowVersion=d.Candidate.RouteRowVersion,WalletRowVersion=d.WalletRowVersion,OperationToken=d.OperationToken,PreviewFingerprint=d.PreviewFingerprint};}
 sealed class Created{public long Id;public string Token;}
 static Created Voucher(long trip,long station){var c=F().GetDriverTrip(trip,2);long request=F().Submit(new SubmitFuelRequest{TripId=trip,TripRowVersion=c.TripRowVersion,AssignmentRowVersion=c.AssignmentRowVersion,SubmissionToken=Guid.NewGuid(),Justification="Synthetic authorization"},2,Now,Utc).FuelRequestId;var r=F().GetRequest(request,1,false);var s=new SqlFuelStationRepository(Connection).GetStation(station,1);string token=FuelRedemptionToken.Create();return new Created{Id=F().Approve(new ApproveFuelRequest{FuelRequestId=request,FuelStationId=station,Quantity=1,Amount=0,ValidUntilLocal=r.Context.ExpectedFinishLocal.AddHours(2),RequestRowVersion=r.RowVersion,TripRowVersion=r.Context.TripRowVersion,AssignmentRowVersion=r.Context.AssignmentRowVersion,BusRowVersion=r.Context.BusRowVersion,StationRowVersion=s.RowVersion},1,FuelRedemptionToken.Hash(token),new byte[32],Now,Utc),Token=token};}
 sealed class Outcome{public object Value;public Exception Error;}
 static Outcome[] Race(Func<object> a,Func<object> b){using(var gate=new Barrier(2)){var tasks=new[]{a,b}.Select(f=>Task.Factory.StartNew(()=>{gate.SignalAndWait();try{return new Outcome{Value=f()};}catch(Exception e){return new Outcome{Error=e};}})).ToArray();Task.WaitAll(tasks);return tasks.Select(t=>t.Result).ToArray();}}
 static void Expect(Action a,string label){bool failed=false;try{a();}catch(MaintenancePersistenceException){failed=true;}catch(TripOperationsPersistenceException){failed=true;}catch(FuelPersistenceException){failed=true;}Check(failed,label);}
 static object Scalar(string sql){using(var c=new SqlConnection(Connection)){c.Open();using(var cmd=new SqlCommand(sql,c))return cmd.ExecuteScalar();}}
 static long Number(string sql){return Convert.ToInt64(Scalar(sql));}
 static void Execute(string sql,DateTime? date=null){using(var c=new SqlConnection(Connection)){c.Open();using(var cmd=new SqlCommand(sql,c)){cmd.Parameters.Add("@Date",SqlDbType.Date).Value=(object)date??DBNull.Value;cmd.ExecuteNonQuery();}}}
 static void Check(bool pass,string label){if(!pass)throw new Exception(label);checks++;}
 sealed class Clock:IClock{public DateTime Value;public DateTime UtcNow{get{return DateTime.SpecifyKind(Value.AddHours(-2),DateTimeKind.Utc);}}public DateTime Today{get{return Value.Date;}}public DateTime OperationalNow{get{return Value;}}public DateTime ToOperationalTime(DateTime utc){return utc.AddHours(2);}}
}
