<%@ Page Title="Change password" Language="C#" AutoEventWireup="true" CodeBehind="ChangePassword.aspx.cs" Inherits="ForteMove.Web.Account.ChangePassword" %>
<!DOCTYPE html><html lang="en"><head runat="server"><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>Change password | ForteMove</title><link runat="server" href="~/Content/vendor/bootstrap.min.css" rel="stylesheet"/><link runat="server" href="~/Content/fortemove.css" rel="stylesheet"/></head>
<body class="login-page"><form id="form1" runat="server"><main class="login-shell"><section class="login-card"><img class="login-wordmark" src="<%= ResolveUrl("~/Content/Brand/fortemove-wordmark.png") %>" alt="ForteMove"/><p class="section-kicker">Account security</p><h1>Choose your password</h1><p>Replace the temporary password before using ForteMove.</p>
<asp:Panel ID="pnlErrors" runat="server" CssClass="alert alert-danger" Visible="false"><asp:Repeater ID="rptErrors" runat="server"><HeaderTemplate><ul class="mb-0"></HeaderTemplate><ItemTemplate><li><%#: Eval("Message") %></li></ItemTemplate><FooterTemplate></ul></FooterTemplate></asp:Repeater></asp:Panel>
<div class="mb-3"><asp:Label runat="server" AssociatedControlID="txtCurrentPassword" CssClass="form-label required-label" Text="Temporary password"/><asp:TextBox ID="txtCurrentPassword" runat="server" TextMode="Password" CssClass="form-control" MaxLength="128" required="required"/></div>
<div class="mb-3"><asp:Label runat="server" AssociatedControlID="txtNewPassword" CssClass="form-label required-label" Text="New password"/><asp:TextBox ID="txtNewPassword" runat="server" TextMode="Password" CssClass="form-control" MaxLength="128" required="required"/><div class="form-text">Use 15–128 characters. Spaces and Unicode are supported.</div></div>
<div class="mb-4"><asp:Label runat="server" AssociatedControlID="txtConfirmPassword" CssClass="form-label required-label" Text="Confirm new password"/><asp:TextBox ID="txtConfirmPassword" runat="server" TextMode="Password" CssClass="form-control" MaxLength="128" required="required"/></div>
<asp:Button ID="btnChangePassword" runat="server" CssClass="btn btn-primary w-100" Text="Change password" OnClick="btnChangePassword_Click"/>
<asp:LinkButton ID="btnSignOut" runat="server" CssClass="btn btn-link w-100 mt-2" Text="Sign out" CausesValidation="false" OnClick="btnSignOut_Click"/>
</section></main></form></body></html>
